# Generated by Django 3.2.4 on 2022-01-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Common',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SYMBOL', models.CharField(max_length=150)),
                ('OPEN', models.FloatField()),
                ('HIGH', models.FloatField()),
                ('LOW', models.FloatField()),
                ('CLOSE', models.FloatField()),
                ('LAST', models.FloatField()),
                ('PREVCLOSE', models.FloatField()),
                ('TOTTRDQTY', models.FloatField()),
                ('TOTTRDVAL', models.FloatField()),
                ('TIMESTAMP', models.DateField()),
                ('TOTALTRADES', models.IntegerField()),
                ('ISIN', models.CharField(max_length=15)),
                ('NAME_OF_COMPANY', models.CharField(max_length=150)),
                ('SERIES', models.CharField(max_length=10)),
                ('DATE_OF_LISTING', models.DateField()),
                ('PAID_UP_VALUE', models.IntegerField()),
                ('ISIN_NUMBER', models.CharField(max_length=150)),
                ('FACE_VALUE', models.CharField(max_length=150)),
            ],
        ),
    ]
